// Edge Function to handle AutoNestCut scheduled report emails
// Deploy this to Supabase Edge Functions

import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    )

    // Check for pending report jobs
    const { data: jobs, error } = await supabaseClient
      .from('report_jobs')
      .select('*')
      .eq('status', 'pending')
      .order('created_at', { ascending: true })
      .limit(5)

    if (error) {
      throw error
    }

    if (!jobs || jobs.length === 0) {
      return new Response(JSON.stringify({ message: 'No pending jobs' }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    let processed = 0
    
    for (const job of jobs) {
      try {
        // Send email using existing Resend setup
        const emailResponse = await fetch('https://api.resend.com/emails', {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${Deno.env.get('RESEND_API_KEY')}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            from: 'AutoNestCut <support@mimevents.com>',
            to: [job.email],
            subject: `AutoNestCut Scheduled Report: ${job.task_name}`,
            html: `
              <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                <h2 style="color: #0078D4;">Your AutoNestCut Report is Ready</h2>
                <p><strong>Task:</strong> ${job.task_name}</p>
                <p><strong>Format:</strong> ${job.format.toUpperCase()}</p>
                <p><strong>Generated:</strong> ${new Date(job.created_at).toLocaleString()}</p>
                <p style="margin: 20px 0;">
                  <a href="${job.file_url}" 
                     style="background: #0078D4; color: white; padding: 12px 24px; text-decoration: none; border-radius: 4px;"
                     download>Download Report</a>
                </p>
                <p>This report was automatically generated by your scheduled AutoNestCut task.</p>
                <p>Best regards,<br>The AutoNestCut Team</p>
              </div>
            `,
          }),
        })

        if (emailResponse.ok) {
          // Mark job as processed
          await supabaseClient
            .from('report_jobs')
            .update({ 
              status: 'sent', 
              processed_at: new Date().toISOString() 
            })
            .eq('id', job.id)
          
          processed++
        } else {
          console.error('Email failed for job:', job.id)
          // Mark as failed
          await supabaseClient
            .from('report_jobs')
            .update({ status: 'failed' })
            .eq('id', job.id)
        }
      } catch (jobError) {
        console.error('Job processing error:', jobError)
        await supabaseClient
          .from('report_jobs')
          .update({ status: 'failed' })
          .eq('id', job.id)
      }
    }

    return new Response(JSON.stringify({ 
      success: true, 
      processed,
      total: jobs.length 
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })

  } catch (error) {
    console.error('Edge function error:', error)
    return new Response(JSON.stringify({ error: error.message }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 500,
    })
  }
})